spring:
  redis:
    # Redis数据库索引（默认为0）、服务器地址、端口
    database: 0
    cluster:
      # redis 集群地址
      nodes: ${filter.redis.cluster.nodes}
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）、最大阻塞等待时间（使用负值表示没有限制）
        max-active: 8
        max-wait: 60000
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 10000